### ISSUE TITLE
[Bug] Compilation failure on the repo tests preventing its usage

### ISSUE THREAD

**Issue by CarlosNihelton** [clean-test/clean-test#4]
First of all, thanks for this awesome work! This library is really interesting!

## The Bug

When trying to build a minimal sample on Windows (latest Visual Studio compiler) using your library through `CMake` `FetchContent` I got stuck on building your tests instead of mine (compilation fails due some tuple magic not succeeding apparently).

## System Details

 - OS: Windows 11
 - Compiler version: MSVC 19.35.32217.1 (Visual Studio 17 2022 Windows SDK version 10.0.22621.0 to target Windows 10.0.25357)
 - Version / commit of Clean Test: d994ea4e3c28177bd763af9dacb9533d554bc7e8

## Reproduce

One CMakeLists.txt file

```cmake
cmake_minimum_required(VERSION 3.17)
project(clean-test-win)

set(CMAKE_CXX_STANDARD 20)

include(FetchContent)
fetchcontent_declare(
  CleanTest
  GIT_REPOSITORY https://github.com/clean-test/clean-test.git
  GIT_TAG        main # or a fixed tag e.g. v1.2.0
)
fetchcontent_makeavailable(CleanTest)

add_executable(clean-test-win test.cpp)
target_link_libraries(clean-test-win CleanTest::main-automatic)
```

and one C++ source file:

```cpp
#include <clean-test/clean-test.h>

constexpr auto sum(auto... vs) { return (0 + ... + vs); }

namespace ct = clean_test;
using namespace ct::literals;

auto const suite = ct::Suite{ "sum", [] {
    "0"_test = [] { ct::expect(sum() == 0_i); };
    "3"_test = [] { ct::expect(sum(1, 2) == 1 + 2_i); };
    "A"_test = [] { ct::expect(sum(-1) < 0_i and sum(+1) > 0_i); };
} };
```

Then the regular CMake workflow:

```sh
cmake -E make_directory _build

cmake -S . -B _build

```
## Observed Behavior

Build fails without even reaching my target (it stopped on failing to compile the library tests on some tuple related concept matching).

## Expected Behavior

By default build only the targets we need in order to use the library.

## Additional Context

The complete build log is available in: https://github.com/CarlosNihelton/CleanTestWin/blob/main/log.txt.
The repository where that file lives also contain the CMakeLists.txt and the C++ source file described above.

I could complete my build successfully and use your library as expected by skipping your tests with `cmake -S . -B _build _DCLEANTEST_TEST=OFF`.

Although it wouldn't solve the real issue, moving the test and documentation build steps into the section which is skipped if `clean-test` is not the top level project, also makes it, with the advantage of making it easy for newcomers to use your library by default. 

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 427fc37..dcbe2ba 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -234,16 +234,17 @@ else ()
     add_library(CleanTest::main-automatic ALIAS cleantest-main-shared)
 endif ()

-if (CLEANTEST_TEST)
-    enable_testing()
-    add_subdirectory(test)
-endif()
-add_subdirectory(doc)
-
-## Packaging ###########################################################################################################
+## Packaging, doc and tests ###########################################################################################################

 # Skip if we are not the toplevel of the cmake build
 if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
+
+    if (CLEANTEST_TEST)
+        enable_testing()
+        add_subdirectory(test)
+    endif()
+    add_subdirectory(doc)
+
     set(CPACK_PACKAGE_NAME                clean-test)
     set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A modern, C++-20 unit-testing framework.")
     set(CPACK_PACKAGE_INSTALL_DIRECTORY   ${CPACK_PACKAGE_NAME})
```

Consider the case of maintainers of a vcpkg port or a conan recipe, for instance, which would benefit from that change by finding their intended usage by default, without the need to tweak CMake variables.

**Comment by CarlosNihelton** [comment]
> Thanks for reporting. Sounds like a valid request to make. I would also accept a PR (the first for Clean Test if you want to take the honor).

My pleasure!

**Comment by m8mble** [comment]
Unrelated to your PR / issue: The tuple problem with MSVC is fixed on main.
