### ISSUE TITLE
Copy of boost-ext::ut ?

### ISSUE THREAD

**Issue by alexpanter** [clean-test/clean-test#9]
Hi,

This unit test framework seems eerily similar to [boost-ext::ut](https://github.com/boost-ext/ut), as was also presented at [cppcon22](https://www.youtube.com/watch?v=-qAXShy1xiE).

Maybe you could contribute to their instead of maintaining a similar, parallel repo (with far less user support).
Or if you are copying their work - maybe close your repo?

Best,
Alexander

**Comment by m8mble** [comment]
Clean Test is inspired by UT and therefore offers a similar API. UT is great, but only Clean Test can
 - introspect generic expressions with short circuiting,
 - execute tests in parallel and handle simultaneous failures correctly,
 - change settings at runtime,
 - run in CI (UTF-8 support, JUnit reports, etc.).
 
Details have been presented at [Meeting C++ 2022](https://www.youtube.com/watch?v=JF83GGNvvM8). You are welcome to contribute to Clean Test.
